# ustawienia
settings:
  startingPoints: 1000
  constantValue: 32
  playersTop: 21
  playersPerPage: 7
  # "inf" (nieskończoność) lub dowolna liczba całkowita
  maxPoints: "inf"
  # "-inf" (minus nieskończoność) lub dowolna liczba całkowita
  minPoints: 0

# wiadomosci
messages:
  eloHeader: "&2Twoje statystyki PVP:"
  eloHeaderOther: "&2Statystyki PVP gracza &f{0}&2:"
  eloKills: "&2Ilosc zabojstw/Ilosc smierci: &f{0}/{1} (&2KDR: &f{2})"
  eloPoints: "&2Punkty: &f{0} &2(&f{1} &2miejsce w rankingu)"
  error: "&4Stalo sie cos zlego i nie mozna wykonac tej komendy. Jesli to sie powtorzy, skontaktuj sie z administracja serwera!"
  noPlayers: "&4Brak graczy w rankingu!"
  playerNotExist: "&4Gracz {0} nie istnieje!"
  topHeader: "&2-----[&f Top {0} graczy w rankingu Elo &2]-----"
  top: "&7{0}. &2{1} &7- &f{2} pkt."
  topMore: "&2Wiecej &7- &f/elotop {0}"
  lostPoints: "Straciles {0} puntkow i masz ich teraz {1}. Jestes na {2} miejscu w rankingu."
  gainedPoints: "Zdobyles {0} puntkow i masz ich teraz {1}. Jestes na {2} miejscu w rankingu."