# ustawienia
settings:
  startingPoints: 1000
  constantValue: 32
  playersTop: 21
  playersPerPage: 7
  logPointsChange: true
  # "inf" (nieskończoność) lub dowolna liczba całkowita
  maxPoints: "inf"
  # "-inf" (minus nieskończoność) lub dowolna liczba całkowita
  minPoints: 0
  # światy, w których liczone są śmierci ([] - wszystkie)
  worlds: []

# wiadomosci
messages:
  eloHeader: "&2Twoje statystyki PVP:"
  eloHeaderOther: "&2Statystyki PVP gracza &f{player}&2:"
  eloKills: "&2Ilosc zabojstw/Ilosc smierci: &f{kills}/{deaths} &2(KDR: &f{kdr}&2)"
  eloPoints: "&2Punkty: &f{points} &2(&f{ranking} &2miejsce w rankingu)"
  error: "&4Stalo sie cos zlego i nie mozna wykonac tej komendy. Jesli to sie powtorzy, skontaktuj sie z administracja serwera!"
  noPlayers: "&4Brak graczy w rankingu!"
  playerNotExist: "&4Gracz {player} nie istnieje!"
  topHeader: "&2-----[&f Top {amount} graczy w rankingu Elo &2]-----"
  top: "&7{lp}. &2{player} &7- &f{points} pkt."
  topMore: "&2Wiecej &7- &f/elotop {page}"
  lostPoints: "&2Straciles &f{lost} &2puntkow i masz ich teraz &f{points}&2. Jestes na &f{ranking} &2miejscu w rankingu."
  gainedPoints: "&2Zdobyles &f{gained} &2puntkow i masz ich teraz &f{points}&2. Jestes na &f{ranking} &2miejscu w rankingu."