# ustawienia
settings:
  startingPoints: 1500
  constantValue: 32
  playersTop: 21
  playersPerPage: 7
  logPointsChange: true
  # liczba calkowita z zakresu <-2147483648; 2147483647>
  maxPoints: 3200
  # liczba calkowita z zakresu <-2147483648; 2147483647>
  minPoints: 0
  # ilosc zapamietanych ostatnich zabojstw
  killsHistory: 5
  # ilosc zapamietanych ostatnich smierci
  deathsHistory: 5
  # swiaty, w ktorych liczone sa smierci ([] - wszystkie)
  worlds: []
  # po ilu dniach nieobecnosci na serwerze usunac statystyki gracza (0 - wylacza)
  removeAfter: 0

# wiadomosci
messages:
  eloHeader: "&2-----[ &fTwoje statystyki PVP &2]-----"
  eloHeaderOther: "&2-----[ &fStatystyki PVP gracza &a{player} &2]-----"
  eloKills: "&2Ilosc zabojstw/Ilosc smierci: &f{kills}/{deaths} &2(KDR: &f{kdr}&2)"
  eloPoints: "&2Punkty: &f{points} &2(&f{ranking} &2miejsce w rankingu)"
  lastKills: "&2Ostatnie zabojstwa: &f{players}"
  lastDeaths: "&2Ostatnie smierci: &f{players}"
  separator: "&a, &f"
  error: "&4Stalo sie cos zlego i nie mozna wykonac tej komendy. Jesli to sie powtorzy, skontaktuj sie z administracja serwera!"
  noPlayers: "&4Brak graczy w rankingu!"
  playerNotExist: "&4Gracz {player} nie istnieje!"
  topHeader: "&2-----[ &fTop &a{amount} &fgraczy w rankingu PVP &2]-----"
  top: "&7{lp}. &2{player} &7- &f{points} pkt."
  topMore: "&2Wiecej &7- &f/elotop {page}"
  lostPoints: "&2Straciles &f{lost} &2puntkow i masz ich teraz &f{points}&2. Jestes na &f{ranking} &2miejscu w rankingu."
  gainedPoints: "&2Zdobyles &f{gained} &2puntkow i masz ich teraz &f{points}&2. Jestes na &f{ranking} &2miejscu w rankingu."
  none: "brak"
  noPermissions: "&4Nie posiadasz uprawnien do wywolania tej komendy!"
  tooManyArgs: "&4Za duzo argumentow!"
  notEnoughArgs: "&4Za malo arguentow!"
  usage: "&2Uzycie: &f{command}"
  integer: "&4Strona musi byc liczba calkowita wieksza od zera!"
  rankingNotReseted: "&4Wystapil blad i nie mozna bylo zresetowac rankingu gracza &f{player}&4!"
  rankingReseted: "&2Zresetowano ranking gracza &f{player} &2."