name: EloPVPRanking
description: Ranking PVP na podstawie punktów Elo.
main: pl.chormon.elopvpranking.EloPVPRanking
author: Chormon
version: "${project.version}"
commands:
  elo:
    description: Ranking elo gracza
    permission: elopvpranking.elo
    usage: /<command> [gracz]
  elotop:
    description: Top graczy w rankingu ELO
    permission: elopvpranking.elotop
    usage: /<command> [strona]
  eloreload:
    description: Przeladowuje plugin
    permissions: elopvpranking.eloreload
    usage: /<command>
  eloinfo:
    description: Informacje o pluginie
    permission: elopvpranking.eloinfo
    usage: /<command>
permissions:
  elopvpranking.*:
    description: Pozwala na uzycie wszystkich komend pluginu EloPVPRating
    children:
       elopvpranking.elo: true
       elopvpranking.elo.others: true
       elopvpranking.elotop: true
  elopvpranking.elo:
    description: Pozwala na sprawdzenie swojego rankingu ELO
    default: true
  elopvpranking.elo.other:
    description: Pozwala na sprawdzenie rankingu ELO innych graczy
    default: op
    children:
       elopvpranking.elo: true
  elopvpranking.elotop:
    description: Pozwala na sprawdzenie topki rankingu ELO
    default: true
  elopvpranking.eloreload:
    description: Pozwala na przeladowanie pluginu
    default: op
  elopvpranking.eloinfo:
    description: Pozwala na wyswietlenie informacji o pluginie
    default: op
      